package edu.neu.madcourse.numad21fa_bello_hiciano_maranon.a7.sign_in;

import androidx.annotation.NonNull;

/**
 * Class representing client registration tokens and the time
 * at which they are registered.
 *
 * @author bello
 */
public class Token {

    public String token;
    public String registerTime;

    /**
     * Generates a Token object, utilizing the token for a particular
     * app instance -- generated by Firebase -- along with the time at
     * which it was registered.
     *
     * @param token - the client register token, used for identifying
     *              specific app instances
     * @param registerTime - the time at which the token is registered
     */
    public Token(String token, String registerTime) {
        this.token = token;
        this.registerTime = registerTime;
    }

    /**
     * Returns the client register token, used for identifying specific
     * app instances
     *
     * @return the client register token, used for identifying specific
     * app instances
     */
    public String getToken() {
        return token;
    }

    /**
     * Returns the time at which the token is registered
     *
     * @return the time at which the token is registered
     */
    public String getRegisterTime() {
        return registerTime;
    }

    /**
     * Provides a String representation of a Token, for logging purposes
     *
     * @return String representation of a Token, for logging purposes
     */
    @NonNull
    @Override
    public String toString() {
        return "Token: " + token +
                ", Register Time: " + registerTime;
    }
}
